#+TITLE:Journal de Bord
#+AUTHOR: Hector Suzanne
#+DATE:<2020-04-06 Mon>

* lun 02 mars
** Installation
Arrivée au LIP6 accueilli par Chailloux.
Logé salle des doctorants, avec
- Mattieu Journault
- Martin Pépin
- Yi-Ting Chen
Ai reçu une clé qui ouvre les couloirs du LIP6, mais pas de la 25-26-303, une
demande à été faite. Ai vu Mme Dacosta et Mme XXX pour les clés. Ai vu Mr
Konstantin Kabassanov pour le compte LIP6
** Compte LIP6
le login est /suzanneh/. Il y a deux mots de passe: un pour les login unix
propres et l'autre pour les autres services. Je suis connecté au Wifi et au
imprimantes du bureau. J'ai configuré mon mail LIP6 sans problème. On se
connecte via ssh à /sphinx.lip6.fr/ même depuis l'extérieur. J'ai installé une
clé RSA fraiche sur mon compte.
*** DONE Adresse MAC de l'adaptateur Ethernet
** RDV avec Chailloux
Je sujet est assez libre, la première étape est donc de se familiariser avec
l'état de l'art via les thèses afférentes et les articles récent. Il faudra
aussi se tenir au jus des avancées dans les mode impératif, notamment Java
(analyses d'échappement). On comparera aussi avec RAML, voire étendre le langage
pour supporter la prog synchrone avec OCaLustre.
J'ai reçu un BBC MicroBit pour la durée du stage, qui servira de banc de test
pour OMicroB.
*** DONE Préparer la bibliographie
** Tests du microbit
Le microbit démarre, le programme par défaut fonctionne.
Le port USB gauche ne laisse pas passer les données, on le branche à droite.
On doit installer la toolchain GNU ARM, via un manager de paquet (ce n'est pas
dit sur le git). Il faut aussi utiliser la branche /microbit-without-mbed/.
Le compilateur fonctionne, mais il faudrait pouvoir flasher plus facilement. Le
test a été fait sur /targets/microbit/tests/basic/.
* mar 03 mars
Arrivée à 9h, on commence la bibliographie sur Zotero, et les recherches.
Objectif: se familiariser avec l'état de l'art sur l'analyse mémoire dans les
langages avec GC. Ai importé la bibliographie de la proposition de sujet de
thèse faite par Chailloux. Ai importé le calendrier des évènements de l'IRILL.
RDV avec Chailloux, on planifie la lecture d'article et la biblio. On s'accorde
sur la fourniture de note de lectures.
Durant la matinée et après le déjeuné, j'ai pu commencer la fiche. Envoi en HTML
à partir du .org à 15h30. On a pris une pause avec l'équipe, puis au retour,
consultation de la bibliographie de TARBAC et joujou avec RAML. On a appris que
Hofmann est en fait le feu directeur de thèse de Hoffmann, mort tragiquement
lors d'une randonnée au Japon
** DONE Importer les PDF derrière un
* mer 04 mars
Arrivé 9h30, petit déj sur place, déjeuner au RA avec la meute & Fredéric P.
Mail de Chailloux à 13h, retour sur la forme des notes sur TARBAC.
* jeu 05 - ven 06 mars
On a révisé pour le dernier examen du MPRI, et on a compilé et testé RAML
* lun 09 mars
Retour au labo, sans examen ni projets à rendre. J'ai commencé à lire la thèse
de Vasconcelos, sur l'analyse de perf.  avec des types à tailles.
* mar 10 mars
Arrivée au retard au LIP6 pour cause de réveil pas entendu.
Programme prévisionnel du jour: lecture de la thèse de Vasconcelos
Avec un casque audio pour essayer.
** DONE Voir DaCosta pour la carte RA
** DONE Faire un git public
* mer 11 mars
Oublié de prendre l'effexor ce matin, vers 12:30 la descente ce fait sentir.
Pas de rechange dans mon sac... Rentré à l'appart pour le prendre. Fin des
symptomes à 15h. Journée un peu ruinée resultat. J'ai pu avancer sur les sized
types dans la thèse de Vasconcelos.
* jeu 12 mars
RDV avec MacLay à 11h, rentré déjeuné à la maison, arrivé au LIP6 à 12:45.
Avancé sur la thèse de Vasconcelos. Impression de albert2008.
Assisté au séminaire "Code source", exposé sur Di Cosmo sur le software heritage
project. Fascinant, éclairant, inspirant.

* ven 13 - lun 16 mars
Symptômes du coronavirus, isolement
rentrée à tours lundi
* mar 17 mars
rien.
* mer 18 mars
rapport d'installation.
** Idée de programme
dessin en 2D, ou l'on se déplace avec les boutton, et flip les leds en secouant.
* jeu 19 - ven 20
rien.
* lun 23 mars
Chailloux se remet, la visio prévue pour aujourd'hui est décalée.
On continue à ce battre contre la thèse de Vasconcelos.
* mar 24 - mer 25 mars
Anniversaires. rien.
* jeu 26 mars
Ambition du jour: fini la p***** de thèse de Vasconcelos: On y est presque.
* ven 27 mars
rien
* lun 30 mars
Vasconcelos, fini !
Fait l'avenant à la convention de stage, qui a été envoyée à Peschanski.
* mar 31 mars - ven 3 avril
- Lecture de albert2008
- Gestion de l'administratif: l'avenant à la convention de stage autorisant le télétravail.
- Meilleur export des notes en HTML
- envoi de ce qui a été fait à Chailloux
* sam 4 - dim 5 avril
On a fini Albert 2008 !
